env:
  browser: true
  es2021: true
  'jest/globals': true
extends:
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - jest
ignorePatterns:
  - .eslintrc.yml
rules:
  comma-dangle:
    - error
    - always-multiline
  space-before-function-paren:
    - off
  '@typescript-eslint/interface-name-prefix':
    - off
  '@typescript-eslint/explicit-function-return-type':
    - off
  '@typescript-eslint/explicit-module-boundary-types':
    - off
  '@typescript-eslint/no-explicit-any':
    - off
  indent:
    - off
  newline-before-return:
    - error
