version: '3.4'

services:
  postgres:
    image: postgres:latest
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=admin'
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    restart: always
    networks:
      - db-network
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redisdata:/bitnami/redis/data
    ports:
      - 6380:6379
volumes:
  appdata: null
  redisdata: null

networks:
  db-network:
    driver: bridge
